all: Client.class Server.class Test.class TestHandler.class TestStubs.class

Client.class: Client.java
	javac Client.java

Server.class: Server.java
	javac Server.java

Test.class: Test.java
	javac Test.java

TestHandler.class: TestHandler.java
	javac TestHandler.java

TestStubs.class: TestStubs.java
	javac TestStubs.java
