// ====================================================================
// Warning.  Do not edit this file directly.  This file is generated
// by rpcgen.  You should edit the original .java file that was used
// to build this file and then re-run the rpcgen generator.
// ====================================================================

import org.apache.xmlrpc.*;
import java.util.*;
import java.io.*;

/**
 * Stub class to talk with the Test XML-RPC web service.
 */
public class TestStubs
{
  private XmlRpcClient _client;

    /**
   * Constructs the stub class.
   *
   * @arg client The XmlRpcClient connection to the server.
   */
  public TestStubs( XmlRpcClient client )
  {
      _client = client;
  }


  public double add( double a, double b ) throws XmlRpcException, IOException
  {
    Vector params = new Vector();

    params.addElement( new Double( a ) );
    params.addElement( new Double( b ) );

    Object result = _client.execute( "Test.add", params );

    return ((Double)result).doubleValue();

  }

  public double subtract( double a, double b ) throws XmlRpcException, IOException
  {
    Vector params = new Vector();

    params.addElement( new Double( a ) );
    params.addElement( new Double( b ) );

    Object result = _client.execute( "Test.subtract", params );

    return ((Double)result).doubleValue();

  }

  public boolean invert( boolean b ) throws XmlRpcException, IOException
  {
    Vector params = new Vector();

    params.addElement( new Boolean( b ) );

    Object result = _client.execute( "Test.invert", params );

    return ((Boolean)result).booleanValue();

  }

  public int add_int( int a, int b ) throws XmlRpcException, IOException
  {
    Vector params = new Vector();

    params.addElement( new Integer( a ) );
    params.addElement( new Integer( b ) );

    Object result = _client.execute( "Test.add_int", params );

    return ((Integer)result).intValue();

  }

  public int subtract_int( int a, int b ) throws XmlRpcException, IOException
  {
    Vector params = new Vector();

    params.addElement( new Integer( a ) );
    params.addElement( new Integer( b ) );

    Object result = _client.execute( "Test.subtract_int", params );

    return ((Integer)result).intValue();

  }

  public String add_string( String a, String b ) throws XmlRpcException, IOException
  {
    Vector params = new Vector();

    params.addElement( a );
    params.addElement( b );

    Object result = _client.execute( "Test.add_string", params );

    return (String)result;

  }

  public double add_array( Vector a ) throws XmlRpcException, IOException
  {
    Vector params = new Vector();

    params.addElement( a );

    Object result = _client.execute( "Test.add_array", params );

    return ((Double)result).doubleValue();

  }

  public String get_name( Hashtable ht ) throws XmlRpcException, IOException
  {
    Vector params = new Vector();

    params.addElement( ht );

    Object result = _client.execute( "Test.get_name", params );

    return (String)result;

  }

}

// ====================================================================
// Warning.  Do not edit this file directly.  This file is generated
// by rpcgen.  You should edit the original .java file that was used
// to build this file and then re-run the rpcgen generator.
// ====================================================================
