// =======================================================================
// Warning. Do not edit this file directly.  This file was built with the
// cm5 generator. You should edit the original data.txt file
// and re-run the generator.
// =======================================================================

struct {
  char *first;
  char *last;
} g_names[] = 
{ 
  { "Larry","Wall" },

  { "Brian","Kerninghan" },

  { "Dennis","Ritchie" },

  { "", "" }
};

// =======================================================================
// Warning. Do not edit this file directly.  This file was built with the
// cm5 generator. You should edit the original data.txt file
// and re-run the generator.
// =======================================================================
