% ==================================================================
%
% WARNING : Do not edit this file by hand.  This file was created
% by uigen.  Edit the definition files and re-generate to make
% modifications.  Making modifications to this file directly will
% result in loss of work when the file is re-generated.
%
% ==================================================================
%
<jsp:useBean id="myBean" class="NameBean" scope=request></jsp:useBean>
<html>
<head>
<title>Edit Name</title>
</head>
<body>

<table>
<tr>

<th>First</th>

<th>Middle</th>

<th>Last</th>

</tr>
% ResultSet result = myBean.query();
% while( result.next ) {
<tr>
<td><%= result.getFirst() %></td>
<td><%= result.getMiddle() %></td>
<td><%= result.getLast() %></td>

</tr>
% }
</table>

</body>
</html>
%
% ==================================================================
%
% WARNING : Do not edit this file by hand.  This file was created
% by uigen.  Edit the definition files and re-generate to make
% modifications.  Making modifications to this file directly will
% result in loss of work when the file is re-generated.
%
% ==================================================================
