<%
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
%>
<%@ page language="java" %>
<%@ page import="gen.*" %>
<%@ page import="java.util.*" %>

<%
  BookSS ssb =
    SSFactory.createBook();

  if(request.getParameter("doSubmit") != null){
    Integer publisherID = (request.getParameter("publisherID").equals("") ? null : Integer.valueOf(request.getParameter("publisherID")));
    Integer newStatus = (request.getParameter("newStatus").equals("") ? null : Integer.valueOf(request.getParameter("newStatus")));

    ssb.updateStatusByPublisher(
      publisherID
      ,newStatus
      );
    ssb.remove();
%>
    <jsp:forward page="BookValueList.jsp" />
<%
  }
%>
<head>
<title>Custom Method Book.updateStatusByPublisher</title>
</head>
<body>
<h1>Custom Method Book.updateStatusByPublisher</h1>
<form>
<table border=0>
<tr>
  <td>publisherID</td>
  <td>
  <input type=text name=publisherID>
  <td>
  Integer 
  </td>
</tr>
<tr>
  <td>newStatus</td>
  <td>
  <input type=text name=newStatus>
  <td>
  Integer 
  </td>
</tr>

</table>
<input type="submit" name="doSubmit">
</form>
</body>
</html>
<%
  ssb.remove();
%>

<%
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
%>
