<%
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
%>
<html>
<head>
<title>List Page Index</title>
</head>
<body>
<h1>List Page Index</h1>
<table border=1>
    <tr><td><b><a href="AuthorValueList.jsp">AuthorValueList</a></b></td></tr>
    <tr><td><b><a href="BookValueList.jsp">BookValueList</a></b></td></tr>
    <tr><td><b><a href="BookWithNamesValueList.jsp">BookWithNamesValueList</a></b></td></tr>
    <tr><td><b><a href="PublisherValueList.jsp">PublisherValueList</a></b></td></tr>
 
</table>
<h2>Custom Methods</h2>
<a href = "BookupdateStatusByPublisherCustom.jsp">Book.updateStatusByPublisher</a><br>

</body>
</html>

<%
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
%>
