<%
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
%>
<%@ page language="java" %>
<%@ page import="gen.*" %>
<%@ page import="java.util.*" %>

<%
  PublisherSS ssb = 
    SSFactory.createPublisher();
  String query = request.getParameter("query");
  Collection coll = null;

  if(query != null){
  }

  if(coll == null) coll = ssb.getAllPublisherValue();
%>

<html>
<head>
<title>PublisherValue List</title>
</head>
<body>
<h1>PublisherValue List</h1>
<table border=1>
  <tr>
  <td><b>Update</b></td>
  <td><b>Delete</b></td>
    <td><b>publisherID</b></td>
    <td><b>name</b></td>
  </tr>
<%
  for(Iterator i = coll.iterator(); i.hasNext(); ){
    PublisherValue val = (PublisherValue)i.next();
%>
  <tr>
  <td><a href="PublisherUpdate.jsp?publisherID=<%= val.getPublisherID() %>&return=PublisherValueList.jsp">Update</a></td>
  <td><a href="PublisherDelete.jsp?publisherID=<%= val.getPublisherID() %>&return=PublisherValueList.jsp">Delete</a></td>
    <td><%= val.getPublisherID() %></td>
    <td><%= val.getName() %></td>
  </tr>
<%
  }
%>
</table>
<a href="PublisherAdd.jsp?return=PublisherValueList.jsp">Add Publisher</a>
<br>
<a href="index.jsp">List Page Index</a>
<p>
 
</body>
</html>
<%
  ssb.remove();
%>

<%
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
%>
