// Test case for the test case builder
#include <stdio.h>

#define IDOK 10
#define IDCANCEL 20

// <test result="3"><a>1</a><b>2</b></test>
// <test result="6"><a>2</a><b>4</b></test>
int add( int a, int b ) { return a + b; }

int main( int argc, char *argv[] )
{
	run_tests();
	printf( "%d\n", add( 1, 2 ) );
	return 0;
}

// <test_start>
/*
 * ==========================================================================
 * WARNING: This code has been generated by 'testgen'. Any modifications
 * you make to it will be lost when it is regenerated.
 * ==========================================================================
 */
static int run_tests()
{

	if ( add( 1, 2 ) != 3 )
	{
		printf( stderr, "Unit test add_1 failed!\n" );
		return 0;
	}

	if ( add( 2, 4 ) != 6 )
	{
		printf( stderr, "Unit test add_2 failed!\n" );
		return 0;
	}

	return 1;
}
/*
 * ==========================================================================
 * WARNING: This code has been generated by 'testgen'. Any modifications
 * you make to it will be lost when it is regenerated.
 * ==========================================================================
 */

// </test_start>







