% ==================================================================
%
% WARNING : Do not edit this file by hand.  This file was created
% by uigen.  Edit the definition files and re-generate to make
% modifications.  Making modifications to this file directly will
% result in loss of work when the file is re-generated.
%
% ==================================================================
%
<jsp:useBean id="myBean" class="NameBean" scope=request></jsp:useBean>
<html>
<head>
<title>Edit Name</title>
</head>
<body>
<form action="form1.jsp" method="post">
<edit name="first" value="<% myBean.getFirst() %>">
<edit name="middle" value="<% myBean.getMiddle() %>">
<edit name="last" value="<% myBean.getLast() %>">

</form>
</body>
</html>
%
% ==================================================================
%
% WARNING : Do not edit this file by hand.  This file was created
% by uigen.  Edit the definition files and re-generate to make
% modifications.  Making modifications to this file directly will
% result in loss of work when the file is re-generated.
%
% ==================================================================
