// =======================================================================
// Warning. Do not edit this file directly.  This file was built with the
// cm6 generator. You should edit the original <%= class_name %>.java file
// and re-run the generator.
// =======================================================================

public class <%= new_class_name %> {
<% fields.each { |field| %>
	protected String _<%= field %>;<% } %>

	public <%= new_class_name %>()
	{ <% fields.each { |field| %>
		_<%= field %> = new String();<% } %>
	}
<% fields.each { |field| %>
	public String get<%= field.capitalize %>() { return _<%= field %>; }
	public void set<%= field.capitalize %>( String value ) { _<%= field %> = value; }
<% } %>
}

// =======================================================================
// Warning. Do not edit this file directly.  This file was built with the
// cm6 generator. You should edit the original <%= class_name %>.java file
// and re-run the generator.
// =======================================================================
