// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
//
// AuthorEntityHome.java

package gen;

import javax.ejb.EJBLocalHome;
import javax.ejb.EJBException;
import javax.ejb.CreateException;
import javax.ejb.FinderException;
import gen.*;

public interface AuthorEntityHome extends EJBLocalHome {
  public AuthorEntity create( 
    Integer authorID
    ,String name
    ,String penName
    ) throws EJBException, CreateException;
  public AuthorEntity findByPrimaryKey(Integer id)
    throws FinderException, EJBException;
  public java.util.Collection findAll(
    ) throws FinderException, EJBException;


}

//
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
