// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
//
// AuthorEntityBean.java

package gen;

import javax.ejb.EntityBean;
import javax.ejb.EntityContext;
import javax.ejb.EJBException;
import jutil.Sequence;
import javax.naming.InitialContext;

public abstract class AuthorEntityBean implements EntityBean {
  transient private EntityContext ctx;

  public static AuthorEntityHome getHome(){
    try {
      InitialContext jndiContext = new InitialContext();
      Object ref = 
        jndiContext.lookup("gen/AuthorEntity");
      AuthorEntityHome home = (AuthorEntityHome)ref;
      return home;
    }catch (Exception e){
      throw new EJBException("AuthorEntityBean.getHome() failed: " + e.getMessage());
    }
  }

  //===================================================================
  public Integer ejbCreate(
    Integer authorID
    ,String name
    ,String penName
    )
  {
    setAuthorID(Sequence.next("Author_authorID_seq"));
    setName(name); 
    setPenName(penName); 

    return null;
  }

  //===================================================================
  public void ejbPostCreate(
    Integer authorID
    ,String name
    ,String penName
    )
  {
    // set CMR fields here
  }

  //===================================================================
  public abstract Integer getAuthorID();
  public abstract void setAuthorID(Integer authorID);
  public abstract String getName();
  public abstract void setName(String name);
  public abstract String getPenName();
  public abstract void setPenName(String penName);

  public void ejbRemove() {}
  public void ejbActivate() {}
  public void ejbPassivate() {}
  public void setEntityContext(EntityContext ctx) { this.ctx = ctx; }
  public void unsetEntityContext() { this.ctx = null; }
  public void ejbLoad() {}
  public void ejbStore() {}
}


//
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
