// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
//
// BookValue.java

package gen;

import java.sql.ResultSet;
import java.sql.SQLException;

public class BookValue implements java.io.Serializable {
  // private member variables
  private Integer bookID;
  private String title;
  private String ISBN;
  private Integer authorID;
  private Integer publisherID;
  private Integer status;
  private Integer numCopies;

  // empty constructor
  public BookValue(){
    bookID = null; 
    title = null; 
    ISBN = null; 
    authorID = null; 
    publisherID = null; 
    status = null; 
    numCopies = null; 
  }

  // ResultSet constructor
  public BookValue(ResultSet rs) throws SQLException {

    if(rs.getObject(1) != null)
      bookID = new Integer(rs.getInt(1));
    else
      bookID = null;

    title = rs.getString(2);

    ISBN = rs.getString(3);

    if(rs.getObject(4) != null)
      authorID = new Integer(rs.getInt(4));
    else
      authorID = null;

    if(rs.getObject(5) != null)
      publisherID = new Integer(rs.getInt(5));
    else
      publisherID = null;

    if(rs.getObject(6) != null)
      status = new Integer(rs.getInt(6));
    else
      status = null;

    if(rs.getObject(7) != null)
      numCopies = new Integer(rs.getInt(7));
    else
      numCopies = null;
  }

  // member variable getters and setters
  
  public Integer getBookID() { return bookID; }
  public void setBookID(Integer bookID){ this.bookID = bookID; }
  
  public String getTitle() { return title; }
  public void setTitle(String title){ this.title = title; }
  
  public String getISBN() { return ISBN; }
  public void setISBN(String ISBN){ this.ISBN = ISBN; }
  
  public Integer getAuthorID() { return authorID; }
  public void setAuthorID(Integer authorID){ this.authorID = authorID; }
  
  public Integer getPublisherID() { return publisherID; }
  public void setPublisherID(Integer publisherID){ this.publisherID = publisherID; }
  
  public Integer getStatus() { return status; }
  public void setStatus(Integer status){ this.status = status; }
  
  public Integer getNumCopies() { return numCopies; }
  public void setNumCopies(Integer numCopies){ this.numCopies = numCopies; }
}

//
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
