<%
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
%>
<%@ page language="java" %>
<%@ page import="gen.*" %>
<%@ page import="java.util.*" %>

<%
  BookSS ssb =
    SSFactory.createBook();
    Integer pk =
      Integer.valueOf(request.getParameter("bookID"));
  BookValue val = ssb.getBookValue(pk);

  if(request.getParameter("doSubmit") != null){
    val.setTitle(request.getParameter("title").equals("") ? null : (request.getParameter("title")));
    val.setISBN(request.getParameter("ISBN").equals("") ? null : (request.getParameter("ISBN")));
    val.setAuthorID(request.getParameter("authorID").equals("") ? null : Integer.valueOf(request.getParameter("authorID")));
    val.setPublisherID(request.getParameter("publisherID").equals("") ? null : Integer.valueOf(request.getParameter("publisherID")));
    val.setStatus(request.getParameter("status").equals("") ? null : Integer.valueOf(request.getParameter("status")));
    val.setNumCopies(request.getParameter("numCopies").equals("") ? null : Integer.valueOf(request.getParameter("numCopies")));

    ssb.update(val);
    ssb.remove();
%>
    <jsp:forward page="BookValueList.jsp" />
<%
  }
%>
<head>
<title>Update Book</title>
</head>
<body>
<h1>Update Book</h1>
<form>
<table border=0>
<tr>
  <td>bookID</td>
  <td>
  <%= val.getBookID() %>
      <input type="hidden" name="bookID" value="<%= val.getBookID() %>">

  </td>
  <td>
  integer 
  
  
  not null
  
  </td>
</tr>
<tr>
  <td>title</td>
  <td>
  <input type="text" name="title" value="<%= ((val.getTitle() == null) ? "" : val.getTitle().toString())  %>">

  </td>
  <td>
  varchar 
  (80)
  
  not null
  
  </td>
</tr>
<tr>
  <td>ISBN</td>
  <td>
  <input type="text" name="ISBN" value="<%= ((val.getISBN() == null) ? "" : val.getISBN().toString())  %>">

  </td>
  <td>
  varchar 
  (80)
  unique
  not null
  
  </td>
</tr>
<tr>
  <td>authorID</td>
  <td>
  <input type="text" name="authorID" value="<%= ((val.getAuthorID() == null) ? "" : val.getAuthorID().toString())  %>">

  </td>
  <td>
  integer 
  
  
  not null
  references <a href="AuthorValueList.jsp">Author</a>
  </td>
</tr>
<tr>
  <td>publisherID</td>
  <td>
  <input type="text" name="publisherID" value="<%= ((val.getPublisherID() == null) ? "" : val.getPublisherID().toString())  %>">

  </td>
  <td>
  integer 
  
  
  not null
  references <a href="PublisherValueList.jsp">Publisher</a>
  </td>
</tr>
<tr>
  <td>status</td>
  <td>
  <input type="text" name="status" value="<%= ((val.getStatus() == null) ? "" : val.getStatus().toString())  %>">

  </td>
  <td>
  integer 
  
  
  not null
  
  </td>
</tr>
<tr>
  <td>numCopies</td>
  <td>
  <input type="text" name="numCopies" value="<%= ((val.getNumCopies() == null) ? "" : val.getNumCopies().toString())  %>">

  </td>
  <td>
  integer 
  
  
  not null
  
  </td>
</tr>

</table>
<input type="submit" name="doSubmit">
</form>
</body>
</html>
<%
  ssb.remove();
%>
<%
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
%>
