<%
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
%>
<%@ page language="java" %>
<%@ page import="gen.*" %>
<%@ page import="java.util.*" %>

<%
  BookSS ssb = 
    SSFactory.createBook();
  String query = request.getParameter("query");
  Collection coll = null;

  if(query != null){
  }

  if(coll == null) coll = ssb.getAllBookValue();
%>

<html>
<head>
<title>BookValue List</title>
</head>
<body>
<h1>BookValue List</h1>
<table border=1>
  <tr>
  <td><b>Update</b></td>
  <td><b>Delete</b></td>
    <td><b>bookID</b></td>
    <td><b>title</b></td>
    <td><b>ISBN</b></td>
    <td><b>authorID</b></td>
    <td><b>publisherID</b></td>
    <td><b>status</b></td>
    <td><b>numCopies</b></td>
  </tr>
<%
  for(Iterator i = coll.iterator(); i.hasNext(); ){
    BookValue val = (BookValue)i.next();
%>
  <tr>
  <td><a href="BookUpdate.jsp?bookID=<%= val.getBookID() %>&return=BookValueList.jsp">Update</a></td>
  <td><a href="BookDelete.jsp?bookID=<%= val.getBookID() %>&return=BookValueList.jsp">Delete</a></td>
    <td><%= val.getBookID() %></td>
    <td><%= val.getTitle() %></td>
    <td><%= val.getISBN() %></td>
    <td><%= val.getAuthorID() %></td>
    <td><%= val.getPublisherID() %></td>
    <td><%= val.getStatus() %></td>
    <td><%= val.getNumCopies() %></td>
  </tr>
<%
  }
%>
</table>
<a href="BookAdd.jsp?return=BookValueList.jsp">Add Book</a>
<br>
<a href="index.jsp">List Page Index</a>
<p>
 
</body>
</html>
<%
  ssb.remove();
%>

<%
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
%>
