// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
//
// BookEntityBean.java

package gen;

import javax.ejb.EntityBean;
import javax.ejb.EntityContext;
import javax.ejb.EJBException;
import jutil.Sequence;
import javax.naming.InitialContext;

public abstract class BookEntityBean implements EntityBean {
  transient private EntityContext ctx;

  public static BookEntityHome getHome(){
    try {
      InitialContext jndiContext = new InitialContext();
      Object ref = 
        jndiContext.lookup("gen/BookEntity");
      BookEntityHome home = (BookEntityHome)ref;
      return home;
    }catch (Exception e){
      throw new EJBException("BookEntityBean.getHome() failed: " + e.getMessage());
    }
  }

  //===================================================================
  public Integer ejbCreate(
    Integer bookID
    ,String title
    ,String ISBN
    ,Integer authorID
    ,Integer publisherID
    ,Integer status
    ,Integer numCopies
    )
  {
    setBookID(Sequence.next("Book_bookID_seq"));
    setTitle(title); 
    setISBN(ISBN); 
    setAuthorID(authorID); 
    setPublisherID(publisherID); 
    setStatus(status); 
    setNumCopies(numCopies); 

    return null;
  }

  //===================================================================
  public void ejbPostCreate(
    Integer bookID
    ,String title
    ,String ISBN
    ,Integer authorID
    ,Integer publisherID
    ,Integer status
    ,Integer numCopies
    )
  {
    // set CMR fields here
  }

  //===================================================================
  public abstract Integer getBookID();
  public abstract void setBookID(Integer bookID);
  public abstract String getTitle();
  public abstract void setTitle(String title);
  public abstract String getISBN();
  public abstract void setISBN(String ISBN);
  public abstract Integer getAuthorID();
  public abstract void setAuthorID(Integer authorID);
  public abstract Integer getPublisherID();
  public abstract void setPublisherID(Integer publisherID);
  public abstract Integer getStatus();
  public abstract void setStatus(Integer status);
  public abstract Integer getNumCopies();
  public abstract void setNumCopies(Integer numCopies);

  public void ejbRemove() {}
  public void ejbActivate() {}
  public void ejbPassivate() {}
  public void setEntityContext(EntityContext ctx) { this.ctx = ctx; }
  public void unsetEntityContext() { this.ctx = null; }
  public void ejbLoad() {}
  public void ejbStore() {}
}


//
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
