<%
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
%>
<%@ page language="java" %>
<%@ page import="gen.*" %>
<%@ page import="java.util.*" %>

<%
  PublisherSS ssb =
    SSFactory.createPublisher();
    Integer pk =
      Integer.valueOf(request.getParameter("publisherID"));
  PublisherValue val = ssb.getPublisherValue(pk);

  if(request.getParameter("doSubmit") != null){
    val.setName(request.getParameter("name").equals("") ? null : (request.getParameter("name")));

    ssb.update(val);
    ssb.remove();
%>
    <jsp:forward page="PublisherValueList.jsp" />
<%
  }
%>
<head>
<title>Update Publisher</title>
</head>
<body>
<h1>Update Publisher</h1>
<form>
<table border=0>
<tr>
  <td>publisherID</td>
  <td>
  <%= val.getPublisherID() %>
      <input type="hidden" name="publisherID" value="<%= val.getPublisherID() %>">

  </td>
  <td>
  integer 
  
  
  not null
  
  </td>
</tr>
<tr>
  <td>name</td>
  <td>
  <input type="text" name="name" value="<%= ((val.getName() == null) ? "" : val.getName().toString())  %>">

  </td>
  <td>
  varchar 
  (80)
  unique
  not null
  
  </td>
</tr>

</table>
<input type="submit" name="doSubmit">
</form>
</body>
</html>
<%
  ssb.remove();
%>
<%
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
%>
