// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
//
// SSFactory.java
// hides jndi details from remote clients such as web pages

package gen;

import gen.*;
import javax.naming.InitialContext;
import javax.rmi.PortableRemoteObject;

public class SSFactory {

  public static BookSS createBook()
    throws javax.naming.NamingException, java.rmi.RemoteException,
      javax.ejb.CreateException
  {
    InitialContext jndiContext = new InitialContext();
    Object ref =
      jndiContext.lookup("gen/BookSS");
    BookSSHome home =
      (BookSSHome)PortableRemoteObject.narrow(ref,
      BookSSHome.class);
    return home.create();
  }

  public static AuthorSS createAuthor()
    throws javax.naming.NamingException, java.rmi.RemoteException,
      javax.ejb.CreateException
  {
    InitialContext jndiContext = new InitialContext();
    Object ref =
      jndiContext.lookup("gen/AuthorSS");
    AuthorSSHome home =
      (AuthorSSHome)PortableRemoteObject.narrow(ref,
      AuthorSSHome.class);
    return home.create();
  }

  public static PublisherSS createPublisher()
    throws javax.naming.NamingException, java.rmi.RemoteException,
      javax.ejb.CreateException
  {
    InitialContext jndiContext = new InitialContext();
    Object ref =
      jndiContext.lookup("gen/PublisherSS");
    PublisherSSHome home =
      (PublisherSSHome)PortableRemoteObject.narrow(ref,
      PublisherSSHome.class);
    return home.create();
  }


  static {
    System.setProperty("java.naming.factory.initial",
      "org.jnp.interfaces.NamingContextFactory");
    System.setProperty("java.naming.provider.url","jnp://localhost:1099");
    System.setProperty("java.naming.factory.url.pkgs",
      "org.jboss.naming:org.jnp.interfaces");
  }
}

//
// ==================================================================
//
// WARNING : Do not edit this file by hand.  This file was created
// by ejbgen.  Edit the definition files and re-generate to make
// modifications.  Making modifications to this file directly will
// result in loss of work when the file is re-generated.
//
// ==================================================================
