// =======================================================================
// Warning. Do not edit this file directly.  This file was built with the
// pc1 generator. You should edit the data.txt file and re-run the generator.
// =======================================================================

public class PersonBase {

  protected String _first;
  protected String _middle;
  protected String _last;

  public PersonBase()
  { 
    _first = new String();
    _middle = new String();
    _last = new String();
  }

  public String getFirst() { return _first; }
  public void setFirst( String value ) { _first = value; }

  public String getMiddle() { return _middle; }
  public void setMiddle( String value ) { _middle = value; }

  public String getLast() { return _last; }
  public void setLast( String value ) { _last = value; }

}

// =======================================================================
// Warning. Do not edit this file directly.  This file was built with the
// pc1 generator. You should edit the data.txt file and re-run the generator.
// =======================================================================
